esphome:
  name: test

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_sid
  password: !secret wifi_pw

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "4BgJ50H82Rsv"

captive_portal:

external_components:
  #- source: github://mohnen/esphome-harmony-companion
  - source:
      type: local
      path: components
    components: [ harmony-companion-hub ]

harmony-companion-hub:
  id: harmony_companion_hub_1
  ce_pin: GPIO4
  csn_pin: GPIO2
  address: 0x44D2964B09

spi:
  - clk_pin: GPIO18
    miso_pin: GPIO19
    mosi_pin: GPIO23
