esphome:
  name: test

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "UseYourOwn"
  password: "UseYourOwn"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "4BgJ50H82Rsv"

captive_portal:

external_components:
  #- source: github://mohnen/esphome-harmony-companion
  - source:
      type: local
      path: components
    components: [ harmony-companion-hub ]

harmony-companion-hub:
  id: harmony_companion_hub_1
  csn_pin: GPIO2
  ce_pin: GPIO5

spi:
  - clk_pin: GPIO1 
    miso_pin: GPIO3
    mosi_pin: GPIO4
